name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: working-directory

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: xtensa-espressif_esp32s3_zephyr-elf

      - name: Build firmware
        working-directory: working-directory
        shell: bash
        run: |
          pwd
          ls -la
          west build -p always -b heltec_wireless_stick_lite_v3/esp32s3/procpu app
          ls -la

      - name: Check path
        shell: bash
        run: |
          pwd

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: zephyr.bin
          path: working-directory/esp-web-flash-demo/build/zephyr/zephyr.bin
